name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: docker compose -f docker-compose.yml build
      - echo: docker images
      
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
        - run: docker compose -f docker-compose.yml up -d

